- name: Contrôle du checksum du fichier/répertoire
  hosts: all
  become: yes
  tasks:
  - name: Vérification du checksum
    stat:
      path: /etc/hosts
    register: sf
  - name: Affichage du checksum
    debug:
      msg: 'Le checksum du fichier {{ sf.stat.path }} : {{ sf.stat.checksum }}'
  - name: Informations
    debug:
      msg: Les valeurs ont été enregistrées dans le fichier checksum.txt

      
  
   
