- name: Génération et déploiement de clef ssh
  hosts: all
  tasks:

  - name: Génération de clef
    openssh_keypair:
      path: /home/vagrant/vagrant
      type: rsa
      size: 4096
      state: present
      force: yes
    delegate_to: localhost
    run_once: yes
  - name: Creation de l'utilisateur helene
    user:
      name: helene
      shell: /bin/bash
      groups: sudo
      append: yes
      password: "{{ 'password' | password_hash('sha512') }}"
    become: yes
  - name: Ajout de l'utilisateur 'helene' aux sudoers
    copy:
      dest: /etc/sudoers.d/helene
      content: 'helene ALL=(ALL) NOPASSWD: ALL'
    become: yes
  - name: Déploiement de la clé ssh
    authorized_key:
      user: helene
      key: "{{ lookup('file', '/home/vagrant/vagrant.pub') }}"
    become: yes
